server:
  port: 3000
spring:
  application:
    name: feng-crowd-redis
  redis:
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000